site_name: Codeball v0.0.4

theme:
  name: material
  palette:
    primary: teal

plugins:
  - search
  - mkdocstrings

nav:
    - Codeball: index.md
    - CodeFrames: codeframes.md
    - Patterns: patterns/patterns.md
    - Metrica Play: patterns-for-play.md
