site_name: Codeball v0.0.4
site_url: https://codeball.metrica-sports.com
repo_url: https://github.com/metrica-sports/codeball
repo_name: 'Codeball'
edit_uri: blob/master/docs/

theme:
  name: material
  palette:
    primary: teal

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
      execute: True

nav:
    - Home: index.md
    - GameDataset: game-dataset.md
    - CodeballFrames: codeball-frames.md
    - Patterns: patterns.md
    - Metrica Play API: 
      - What you can do: metrica-play-api.md
      - Patterns and tags: format-for-play.md
      - Visualizations: visualiztions.md
    - Examples:
      - GameDataset: examples/game_dataset.ipynb
      - Example pattern: examples/example-pattern.md
      - Run patterns: examples/run_patterns.ipynb
      
      
